### ISSUE TITLE
Why error! So sad bro.

### ISSUE THREAD

**Issue by 1Dreamer666** [CheesyBurrito/Java-Doom#1]
Current search path:
~/.local/share/Steam/steamapps/common/doom 3/base
game DLL: 0x0 in pak: 0x0
Addon pk4s:
file syastem initialized.
--------------------------------------
^3WARNING: ^1idFileSystemLocal::StartBackgroundDownloadThread: failed
Unknown command 'vid_restart'
idSessionLocal::StopRecordingRenderDemo: not recording
--------- Game Map Shutdown ----------
--------------------------------------
idRenderSystem::Shutdown()
------------ Game Shutdown -----------
--------- Game Map Shutdown ----------
--------------------------------------
neo.TempDump$TODO_Exception

**Comment by wagrenier** [comment]
I think you got the wrong repo

**Comment by 1Dreamer666** [comment]
neo.TempDump$TODO_Exception
	at neo.Game.Animation.Anim_Import$idModelExport.Shutdown(Anim_Import.java:436)
	at neo.Game.Game_local$idGameLocal.Shutdown(Game_local.java:846)
	at neo.framework.Common$idCommonLocal.UnloadGameDLL(Common.java:2160)
	at neo.framework.Common$idCommonLocal.ShutdownGame(Common.java:1549)
	at neo.framework.Common$idCommonLocal.Shutdown(Common.java:582)
	at neo.framework.Common$idCommonLocal.FatalError(Common.java:1330)
	at neo.framework.FileSystem_h$idFileSystemLocal.Init(FileSystem_h.java:1089)
	at neo.framework.Common$idCommonLocal.InitGame(Common.java:1391)
	at neo.framework.Common$idCommonLocal.Init(Common.java:543)
	at neo.sys.win_main.main(win_main.java:1686)
Woe to you, Oh Earth and Sea, for the Devil sends the
beast with wrath, because he knows the time is short...
Let him who hath understanding reckon the number of the beast,
for it is a human number,
its numbers, is
